//
// This file is automatically generated by the build system, do not edit!!
// Generated by make on Sun Mar 20 01:04:31 PM EDT 2022
//
#ifndef LUPINE_VERSION_H_INCLUDED
#define LUPINE_VERSION_H_INCLUDED
#define LUPINE_MAJOR 0
#define LUPINE_MINOR 0
#define LUPINE_RELTYPE "alpha"
#define LUPINE_VERSION_STRING "Lupine 0.0-alpha"
#endif
